---
name: Badge

on:
  workflow_call:
    inputs:
      gistID:
        required: false
        type: string
        default: e2729bfd9b81d9c032ded617a3f924e7
      filename:
        required: false
        type: string
        default: 'badge.json'
      label:
        required: false
        type: string
        default: 'DK4'
      message:
        required: false
        type: string
        default: 'Rocks'
      color:
        required: false
        type: string
        default: 'green'
      valColorRange:
        required: false
        type: string
      minColorRange:
        required: false
        type: string
      maxColorRange:
        required: false
        type: string
    secrets:
      GIST:
        required: true

jobs:
  Badge:
    name: Badge
    runs-on: ubuntu-22.04 # ubuntu-latest
    steps:
      - name: Show linters config
        run: ls -alih "${GITHUB_WORKSPACE}/repository/.github/linters"
      - name: Show linters config
        run: ls -alih "${GITHUB_WORKSPACE}/repository/.github/linters"

OWNER="dennykorsukewitz"
REPO="DK4"
WORKFLOW="My Workflow"

# gh run list --repo $OWNER/$REPO

# gh run list --repo $OWNER/$REPO --workflow 'GitHub Pages 2'


# list workflows
WORKFLOW_IDS=($(gh api repos/$OWNER/$REPO/actions/workflows | jq '.workflows[] | .id')) && echo $WORKFLOW_IDS

for WORKFLOW_ID in "${WORKFLOW_IDS[@]}"
do
 echo "Listing runs for the workflow ID $WORKFLOW_ID"
 run_ids=( $(gh api repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_ID/runs --paginate | jq '.workflow_runs[].id') )
 for run_id in "${run_ids[@]}"
 do
   echo "Deleting Run ID $run_id"
   gh api repos/$OWNER/$REPO/actions/runs/$run_id -X DELETE >/dev/null
 done
done


