---
name: GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["dev", "update-dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Lint:
    uses: dennykorsukewitz/DK4/.github/workflows/reusable.pages.yml@dev
