---
name: Trigger GitHub Pages

on:
  workflow_call:

jobs:
  Trigger-GitHub-Pages:
    name: Trigger GitHub Pages
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions: write-all
    # permissions:
    #   actions: write
    steps:
      - run: gh workflow run --repo dennykorsukewitz/dennykorsukewitz.github.io pages.yml --ref dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
